name: ProtocolSupportEasyMultiAccount
main: protocolsupporteasymultiaccount.ProtocolSupportEasyMultiAccount
version: ${version}
api-version: 1.16
load: STARTUP
depend: [ProtocolSupport]

website: 'https://github.com/ProtocolSupport/ProtocolSupportEasyMultiAccount'
author: _Shevchik_
